- name: play level variables
  connection: local
  hosts: local
  vars:
    COURSE: DevSecOps with AWS #it is equal to course=DevSecOps with AWS, we shall refer $var or ${var}
    DURATION: 120 hr+
    TRAINER: Sivakumar
  tasks:
    name: print course info
    ansible.builtin.debug:
      msg: " I'm learning { COURSE } with duration of { DURATION } and trainer is { TRAINER } "