- name: Variables from file
  connection: local
  hosts: local
  vars-file: 
  - course.yaml
  tasks:
  - name: print course info 
    ansible.builtin.debug:
      msg: "Hi {{ Greeting }}, I'm learning {{ Course }} with the duration of {{ Duration }} and trainer is {{ Trainer }}"