- name: Understand vars preference
  connection: local
  hosts: local
  # vars:
  #   Greeting: "Good Morning!"

  # vars_files:
  # - course.yaml

  # vars_prompt:
  # - name: Greeting
  #   prompt: please enter the Greeting
  #   private: false 

  tasks:
    - name: Greeting
      # vars:
      #   Greeting: "Morning!"
      ansible.builtin.debug:
        msg: "{{ Greeting }}"

# Preferences
# 1.Commandline
# 2.task level
# 3.from vars-file
# 4.from vars_prompt
# 5.from play-level

