- name: Installing packages using loops
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
     name: "{{ name }}"
     state: installed
    loop:
    - nginx
    - zip
    - Python
